package POJO;
// Generated 29 Jul, 2023 11:18:40 AM by Hibernate Tools 4.3.1

import java.util.Date;





/**
 * Studenttable generated by hbm2java
 */
public class Studenttable  implements java.io.Serializable {


     private Integer sid;
     private String sfname;
     private String slname;
     private Date age;
     private String email;
     private Integer mobile;
     private String saddress;
     private String scity;
     private String sadmission;
     private String branch;
     private Integer szip;

    public String getSaddress() {
        return saddress;
    }

    public void setSaddress(String saddress) {
        this.saddress = saddress;
    }

    public String getScity() {
        return scity;
    }

    public void setScity(String scity) {
        this.scity = scity;
    }

    public String getSadmission() {
        return sadmission;
    }

    public void setSadmission(String sadmission) {
        this.sadmission = sadmission;
    }

    public String getBranch() {
        return branch;
    }

    public void setBranch(String branch) {
        this.branch = branch;
    }

    public Integer getSzip() {
        return szip;
    }

    public void setSzip(Integer szip) {
        this.szip = szip;
    }

    public Studenttable() {
    }

    public Studenttable(Integer sid, String sfname, String slname, Date age, String email, Integer mobile, String saddress, String scity, String sadmission, String branch, Integer szip) {
        this.sid = sid;
        this.sfname = sfname;
        this.slname = slname;
        this.age = age;
        this.email = email;
        this.mobile = mobile;
        this.saddress = saddress;
        this.scity = scity;
        this.sadmission = sadmission;
        this.branch = branch;
        this.szip = szip;
    }

    
   
    public Integer getSid() {
        return this.sid;
    }
    
    public void setSid(Integer sid) {
        this.sid = sid;
    }
    public String getSfname() {
        return this.sfname;
    }
    
    public void setSfname(String sfname) {
        this.sfname = sfname;
    }
    public String getSlname() {
        return this.slname;
    }
    
    public void setSlname(String slname) {
        this.slname = slname;
    }
    public Date getAge() {
        return this.age;
    }
    
    public void setAge(Date age) {
        this.age = age;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Integer getMobile() {
        return this.mobile;
    }
    
    public void setMobile(Integer mobile) {
        this.mobile = mobile;
    }




}


